### ISSUE TITLE
デザインの調整

### ISSUE THREAD

**Issue by morizooo** [to4iki/conference-app-2017-ios#28]

**Comment by to4iki** [comment]
- タブのデザイン設定はここです https://github.com/to4iki/conference-app-2017-ios/blob/master/conference-app-2017/presentation/viewController/ConferenceViewController.swift#L25-L28
    - see also: [XLPagerTabStripの使い方とカスタマイズ - Qiita](http://qiita.com/KikurageChan/items/35593dc3aac8d694db8e)
- timetable.cellのレイアウトはここです https://github.com/to4iki/conference-app-2017-ios/blob/master/conference-app-2017/presentation/view/timetable/TrackTitleCell.swift#L24-L27 (/timetable/〇〇Cell全て対象)
- navigation barのレイアウトはこちらを参考に [[Swift] ナビゲーションバーのデザインを変更する - YoheiM .NET](http://www.yoheim.net/blog.php?q=20160705)
