### ISSUE TITLE
QRコード読み込み結果をキャッシュする

### ISSUE THREAD

**Issue by morizooo** [to4iki/conference-app-2017-ios#65]
再投票でQRコードを再度読み込むのは手間

**Comment by to4iki** [comment]
iOS11より、標準カメラアプリでQRコードを読み取れるようになったので、
アプリ内QRコード読み取り機能の必要性と合わせて再検討したい。
なので、一旦closeします。

**Comment by yutailang0119** [comment]
UnivarsalLink対応したい！
